// Variables and Data Exercises here
let fullName = "Edison Tong";
console.log(fullName);
console.log(typeof fullName);
console.log(fullName.toUpperCase());
console.log(fullName.toLowerCase());
let age = "25";
let ageIn2Years = age + 2;
console.log(ageIn2Years);
console.log(typeof ageIn2Years);
ageIn2Years = parseInt(age) + 2;
console.log(ageIn2Years);
console.log(typeof ageIn2Years);
let charge = 10;
let payment = 8;
let remaining = charge - payment;
console.log(remaining);
console.log(typeof remaining);
let tests = 97;
let assignments = 77;
let final = 99;
let grade = (tests + assignments + final) / 3;
console.log(grade);
console.log(typeof grade);
let likesVegetables = true;
console.log(likesVegetables);
console.log(typeof likesVegetables);
let pH = 7;
let isAcidic = pH < 7;
console.log(isAcidic);
console.log(typeof isAcidic);
let numberOfSoldiers = 2;
let isSparta = numberOfSoldiers === 300;
console.log(isSparta);
console.log(typeof isSparta);
